### ISSUE TITLE
Please resync your module in TF registry

### ISSUE THREAD

**Issue by mayank0202** [cloudposse/terraform-aws-budgets#40]
### Describe the Bug

https://registry.terraform.io/modules/cloudposse/budgets/aws/0.4.0

This should be `0.4.1` as the latest in TF registry instead of `0.4.0`

### Expected Behavior

There should be 0.4.1 in TF registry which can be shown , you just need to login to TF registry and there is a button called resync module which will fetch the latest tag in registry again

### Steps to Reproduce

Checkout 
https://registry.terraform.io/modules/cloudposse/budgets/aws/0.4.0

**Comment by mayank0202** [comment]
@osterman  Can you take a look on this please?

**Comment by osterman** [comment]
I have resync'd the module. Sorry, the HashiCorp registry has some issues with random modules. It's supposed to update these automatically, but doesn't always work.

**Comment by mayank0202** [comment]
@osterman  No problem , It happens sometimes with registry , Thanks
